notifications:
  irc: "chat.freenode.net#meta-toolkit"

language: cpp

sudo: false

cache:
  directories:
    deps/icu

addons:
  apt:
    packages: &default-packages
      - libjemalloc-dev
      - zlib1g-dev

matrix:
  include:
    # Linux/GCC 4.8
    - os: linux
      env: COMPILER=gcc GCC_VERSION=4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default-packages
            - gcc-4.8
            - g++-4.8

    # Linux/GCC 4.9
    - os: linux
      env: COMPILER=gcc GCC_VERSION=4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default-packages
            - gcc-4.9
            - g++-4.9

    # Linux/GCC 5
    - os: linux
      env: COMPILER=gcc GCC_VERSION=5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default-packages
            - gcc-5
            - g++-5

    # Linux/GCC 6
    - os: linux
      env: COMPILER=gcc GCC_VERSION=6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default-packages
            - gcc-6
            - g++-6

    # Linux/Clang 3.8
    - os: linux
      env: COMPILER=clang CLANG_VERSION=3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - *default-packages
            - clang-3.8

    # Linux/Clang 3.8 + libc++-3.9
    # (I want this to be 3.9 across the board, but the apt source is not
    # yet whitelisted for llvm 3.9)
    - os: linux
      env:
        - COMPILER=clang
        - CLANG_VERSION=3.8
        - LLVM_TAG=RELEASE_390
        - LIBCXX_EXTRA_CMAKE_FLAGS=-DLIBCXX_INSTALL_EXPERIMENTAL_LIBRARY=On
        - CMAKE_VERSION=3.4.3
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - *default-packages
            - clang-3.8

    # OS X 10.10 + Xcode 7.1.1
    - os: osx
      osx_image: xcode7.1
      env: COMPILER=clang

    # OS X 10.11 + Xcode 7.3
    - os: osx
      osx_image: xcode7.3
      env: COMPILER=clang

    # OS X 10.11 + Xcode 8
    - os: osx
      osx_image: xcode8
      env: COMPILER=clang

    # OS X/GCC 6
    - os: osx
      osx_image: xcode7.3
      env: COMPILER=gcc

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source travis/install_linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then source travis/install_osx.sh; fi

before_script:
  - mkdir build
  - cd build
  - cp ../config.toml ./

script:
  - git submodule update --init --recursive
  - ../travis/cmake.sh Debug && make -j2 && make clean && rm -rf CMake* && ../travis/cmake.sh Release && make -j2 && ./unit-test --reporter=spec
